#!/bin/bash

print_cyan() {
    echo -e "\033[36m$1\033[0m"
}

echo "================================================"
print_cyan "          Welcome to Command Kit!"
echo "================================================"
echo
echo "  Run the ./config.sh to configure the environment"
echo
echo "  Available Commands:"
echo "  -------------------"
echo

# SYSTEM UTILITIES
echo "  SYSTEM UTILITIES"
echo "  ----------------"
echo "      config-libs"
echo "        - Installs all required libraries."
echo

# DEVELOPMENT and GIT
echo "  DEVELOPMENT and GIT"
echo "  --------------------"
echo "      git-pull"
echo "        - Runs 'git pull' automatically for multiple repositories in the current directory."
echo
echo "      open-repo <github-repo>"
echo "        - Opens your GitHub project folders in VS Code."
echo "        - Note: Update the 'base_directory' variable with the directory"
echo "          where your projects are stored. Requires 'code .' to be set up."
echo

echo "================================================"
